### ISSUE TITLE
About im2mesh

### ISSUE THREAD

**Issue by renhaofan** [mabaorui/Noise2NoiseMapping#3]
I noticed you use im2mesh.utils package, but it doesn't appear in tf.yml.  

I found it in [occupancy_network](https://github.com/autonomousvision/occupancy_networks/blob/master/im2mesh/utils/__init__.py) , which based on pytorch rather than tf in your env provided.

Any advice on solving this issue ?

**Comment by renhaofan** [comment]
Follow here to solve https://github.com/mabaorui/NeuralPull

**Comment by Wtk0930** [comment]
> Follow here to solve https://github.com/mabaorui/NeuralPull

@renhaofan Hi, have you solved the environment problem, I cannot run the code for the version problem. Can you kindly offer me some advice.
